### ISSUE TITLE
fix the background theme

### ISSUE THREAD

**Issue by BhaktaGopal** [BhaktaGopal/online_Dictionary#16]

**Comment by mateusabelli** [comment]
Hello, could you please assign me for this issue?

**Comment by Harshul02** [comment]
Hello, please assign this to me.

**Comment by doctype-Melvin** [comment]
I have a great idea for this. But maybe, I'm too late.

**Comment by aniket2003** [comment]
@BhaktaGopal Can you please assign me with this I would like to work on this.

**Comment by abhishekpatil4** [comment]
@BhaktaGopal  Please assign me this issue, I'm an experienced Full stack developer, specifically in UI/UX. You can expect the modification soon!

**Comment by BhaktaGopal** [comment]
@mateusabelli ,@doctype-Melvin 
Both of you can work on it and the better will be merged
