### ISSUE TITLE
add a search bar 

### ISSUE THREAD

**Issue by BhaktaGopal** [BhaktaGopal/online_Dictionary#3]
add a search bar to search for a particular word and it's definition/meaning

**Comment by CDPhu** [comment]
Can you assign me this issue? and are you ok with me changing the UI a bit?

**Comment by astrokachi** [comment]
I would like to be assigned to this issue.

**Comment by Arman-ali-khan-786** [comment]
assign it to me @BhaktaGopal

**Comment by BhaktaGopal** [comment]
> assign it to me @BhaktaGopal

sure

**Comment by BhaktaGopal** [comment]
> Can you assign me this issue? and are you ok with me changing the UI a bit?

create a new issue for that ui part
